### ISSUE TITLE
example code does not work on codepen

### ISSUE THREAD

**Issue by Kayoti** [HunterLarco/voxel.css#13]
https://codepen.io/wesbos/pen/EPLVMv?editors=0110
Nothing renders when you visit the link on chrome and firefox

**Comment by HunterLarco** [comment]
Can you explain more what OS you are on. It works on both chrome and firefox on my system. Thanks!

**Comment by Kayoti** [comment]
Hello The permission for webcam was blocked but when i allowed the code worked
