### ISSUE TITLE
Back-face rendering issue in Chrome 48 on a Nexus 4

### ISSUE THREAD

**Issue by AlexYates** [HunterLarco/voxel.css#27]
~~I've a screenshot to attach, but I'm on mobile right now...~~

Updated with screenshot below:
![screenshot_2016-02-26-08-09-25](https://cloud.githubusercontent.com/assets/1916963/13346808/eba56e90-dc60-11e5-98d3-dd7123164a41.png)

**Comment by Heath123** [comment]
Why did you close this?
